### ISSUE TITLE
Search appears to hang

### ISSUE THREAD

**Issue by bdionne** [protegeproject/lucene-search-tab#4]
One of the modelers reports the search hanging, but the console shows a null pointer. Looks to me like an issue with the index directory? Pretty sure this is on windows

```
---------
NCI Edit Tab initialized
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
        at org.apache.lucene.index.DirectoryReader.indexExists(DirectoryReader.j
ava:289) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.engine.SearchTabManager.perfor
mSearch(SearchTabManager.java:245) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.ui.QueryEditorPanel.lambda$new
$2(QueryEditorPanel.java:144) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1
.8.0_91]

```

**Comment by bdionne** [comment]
Here's another stack from the same user. Gilberto tried the same query on his machine and it worked (but produced 0 results)

```
Rebuilding index
Unable to open the ontology owlapi:ontology76791615064924
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.RuntimeException: java.net.MalformedURLException: Unknown protocol: ow
lapi
        at edu.stanford.protege.search.lucene.tab.engine.SearchTabManager.should
StoreInDisk(SearchTabManager.java:296) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.engine.SearchTabManager.loadIn
dexDirectory(SearchTabManager.java:268) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.engine.SearchTabManager.rebuil
dIndex(SearchTabManager.java:142) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.ui.IndexAction.actionPerformed
(IndexAction.java:27) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1
.8.0_91]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[
na:1.8.0_91]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[
na:1.8.0_91]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_
91]
        at javax.swing.AbstractButton.doClick(Unknown Source) ~[na:1.8.0_91]
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source) ~[na:1
.8.0_91]
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown
Source) ~[na:1.8.0_91]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_91]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_9
1]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[n
a:1.8.0_91]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na
:1.8.0_91]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8
.0_91]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [
na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:
1.8.0_91]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [
na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_91]

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_91]

        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_91]
Caused by: java.net.MalformedURLException: Unknown protocol: owlapi
        at java.net.URL.<init>(Unknown Source) ~[na:1.8.0_91]
        at java.net.URL.<init>(Unknown Source) ~[na:1.8.0_91]
        at java.net.URL.<init>(Unknown Source) ~[na:1.8.0_91]
        at java.net.URI.toURL(Unknown Source) ~[na:1.8.0_91]
        at edu.stanford.protege.search.lucene.tab.engine.SearchTabManager.should
StoreInDisk(SearchTabManager.java:288) ~[na:na]
        ... 41 common frames omitted
Caused by: java.lang.IllegalStateException: Unknown protocol: owlapi
        at org.apache.felix.framework.URLHandlersStreamHandlerProxy.parseURL(URL
HandlersStreamHandlerProxy.java:373) ~[org.apache.felix.main.jar:na]
        ... 46 common frames omitted
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
        at org.apache.lucene.index.DirectoryReader.indexExists(DirectoryReader.j
ava:289) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.engine.SearchTabManager.perfor
mSearch(SearchTabManager.java:245) ~[na:na]
        at edu.stanford.protege.search.lucene.tab.ui.QueryEditorPanel.lambda$new
$2(QueryEditorPanel.java:144) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1
.8.0_91]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[
na:1.8.0_91]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[
na:1.8.0_91]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_
91]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce) ~[na:1.8.0_91]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_91]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_9
1]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[n
a:1.8.0_91]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na
:1.8.0_91]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8
.0_91]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_91]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_91]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [
na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:
1.8.0_91]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [
na:1.8.0_91]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_91]

        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_91]

        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_91]
LOGBACK: No context given for org.protege.editor.core.log.LogManager$1[null]
```

**Comment by rsgoncalves** [comment]
This repo is just for the Lucene UI. The issue should be in https://github.com/protegeproject/lucene-search-plugin

**Comment by rsgoncalves** [comment]
I was under the impression that all the logic was coming from the search-plugin, but no.
